int32 player1_score
int32 player2_score

int32 player1_capacity
int32 player2_capacity

int32 player1_paper_count
int32 player1_plastic_count
int32 player1_glass_count

int32 player2_paper_count
int32 player2_plastic_count
int32 player2_glass_count

int32 remaining_trash

bool game_finished
string status

int32[] trash_id
string[] trash_type
float64[] trash_x
float64[] trash_y
float64[] trash_radius
bool[] trash_collected

float64 station_x
float64 station_y
float64 station_radius

float64[] circle_obstacles_x
float64[] circle_obstacles_y
float64[] circle_obstacles_radius

float64[] rectangle_obstacles_x
float64[] rectangle_obstacles_y
float64[] rectangle_obstacles_width
float64[] rectangle_obstacles_height

float64[] player1_path_x
float64[] player1_path_y
float64[] player2_path_x
float64[] player2_path_y